### ISSUE TITLE
Ameli Reyes Hernández 1B

### ISSUE THREAD

**Issue by AmeliReyesHernandez** [SistemasTecTlaxiaco/actividad-2-infografia-AmeliReyesHernandez#1]
![CONSTRUCCION DEL CONOCIMIENTO](https://user-images.githubusercontent.com/112219336/187790037-d328bad4-f154-479c-a8eb-665888f0294c.png)

**Comment by Daisy-GonzalezLita12** [comment]
18.5

**Comment by josealfredo79** [comment]
Bien hecho y revisado...
